#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3
  - python3-pip
  - python3-venv
  - git
  - nginx

runcmd:
  - git clone https://github.com/jagannath-p-s/StarScore.git /home/ubuntu/StarScore
  - cd /home/ubuntu/StarScore
  - python3 -m venv myenv
  - . myenv/bin/activate
  - pip install -r requirements.txt
  - cp /home/ubuntu/StarScore/star_score.service /etc/systemd/system/star_score.service
  - systemctl daemon-reload
  - systemctl start star_score
  - systemctl enable star_score
  - cp /home/ubuntu/StarScore/nginx.conf /etc/nginx/sites-available/star_score
  - ln -s /etc/nginx/sites-available/star_score /etc/nginx/sites-enabled
  - systemctl restart nginx
  - ufw allow 'Nginx Full'
